// AUTO-GENERATED by scripts/gen-lastmod.mjs. Do not edit by hand.
//
// Per-page last-content-change timestamps, taken from the newest commit across
// each route's own source graph. Regenerated before every production build.

export const ROUTE_LASTMOD: Record<string, string> = {
  "/": "2026-07-30T10:17:59Z",
  "/features": "2026-07-30T10:18:12Z",
  "/how-it-works": "2026-07-30T10:18:12Z",
  "/communities": "2026-07-30T10:18:12Z",
  "/trust": "2026-07-30T10:18:12Z",
  "/faq": "2026-07-30T10:17:59Z",
  "/security": "2026-07-30T10:18:12Z",
  "/privacy/request": "2026-07-30T10:18:12Z",
};

/** ISO timestamp for a route, or undefined when history is unknown. */
export function lastmodFor(path: string): string | undefined {
  return ROUTE_LASTMOD[path];
}
