#!/usr/bin/env node
/**
 * Generates src/lib/route-lastmod.generated.ts.
 *
 * <lastmod> must be an authoritative, page-specific "last content change"
 * timestamp. Build time, deploy time or a shared constant are non-page-specific
 * fallbacks that crawlers ignore, so this script derives each route's value
 * from version control instead: the newest commit date across the route file
 * and every first-party module it statically imports (its sections,
 * components and copy). Editing a page's copy moves only that page's date.
 *
 * Runs before every production build, so a deployment always ships the
 * freshest per-page metadata. If git history is unavailable (shallow or
 * missing checkout), the previously generated file is left untouched.
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(root, "src/lib/route-lastmod.generated.ts");

/** Indexable route -> entry source file. Mirrors ROUTE_POLICY. */
const ROUTE_FILES = {
  "/": "src/routes/index.tsx",
  "/features": "src/routes/features.tsx",
  "/how-it-works": "src/routes/how-it-works.tsx",
  "/communities": "src/routes/communities.tsx",
  "/trust": "src/routes/trust.tsx",
  "/faq": "src/routes/faq.tsx",
  "/security": "src/routes/security.tsx",
  "/privacy/request": "src/routes/privacy/request.tsx",
};

const EXTS = [".tsx", ".ts", ".jsx", ".js", ".json", "/index.tsx", "/index.ts"];

function resolveSpecifier(spec, fromFile) {
  let base;
  if (spec.startsWith("@/")) base = path.join(root, "src", spec.slice(2));
  else if (spec.startsWith(".")) base = path.resolve(path.dirname(fromFile), spec);
  else return null; // node_modules: not our content
  if (existsSync(base) && !existsSync(base + ".tsx")) {
    const stat = readFileSync;
    try {
      stat(base);
      return base;
    } catch {
      /* directory */
    }
  }
  for (const ext of EXTS) {
    const candidate = base + ext;
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

const IMPORT_RE =
  /(?:import|export)[\s\S]*?from\s*["']([^"']+)["']|import\s*\(\s*["']([^"']+)["']\s*\)/g;

/** All first-party files a route depends on, transitively. */
function collectSources(entry) {
  const seen = new Set();
  const queue = [path.join(root, entry)];
  while (queue.length) {
    const file = queue.pop();
    if (!file || seen.has(file) || !existsSync(file)) continue;
    seen.add(file);
    const src = readFileSync(file, "utf8");
    for (const match of src.matchAll(IMPORT_RE)) {
      const spec = match[1] ?? match[2];
      if (!spec) continue;
      const resolved = resolveSpecifier(spec, file);
      if (resolved) queue.push(resolved);
    }
  }
  return [...seen];
}

function lastCommitISO(files) {
  let newest = null;
  for (const file of files) {
    const rel = path.relative(root, file);
    let out = "";
    try {
      out = execFileSync("git", ["log", "-1", "--format=%cI", "--", rel], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
    } catch {
      return null; // git unusable
    }
    if (!out) continue;
    if (!newest || out > newest) newest = out;
  }
  return newest;
}

function gitAvailable() {
  try {
    execFileSync("git", ["rev-parse", "--is-inside-work-tree"], {
      cwd: root,
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

if (!gitAvailable()) {
  console.log("[lastmod] git history unavailable, keeping the existing generated file.");
  process.exit(0);
}

const entries = {};
for (const [route, file] of Object.entries(ROUTE_FILES)) {
  const sources = collectSources(file);
  const iso = lastCommitISO(sources);
  if (iso) entries[route] = iso;
  console.log(
    `[lastmod] ${route.padEnd(18)} ${iso ?? "(no history, omitted)"}  <- ${sources.length} file(s)`,
  );
}

if (Object.keys(entries).length === 0) {
  console.log("[lastmod] no timestamps resolved, keeping the existing generated file.");
  process.exit(0);
}

const body = `// AUTO-GENERATED by scripts/gen-lastmod.mjs. Do not edit by hand.
//
// Per-page last-content-change timestamps, taken from the newest commit across
// each route's own source graph. Regenerated before every production build.

export const ROUTE_LASTMOD: Record<string, string> = ${JSON.stringify(entries, null, 2)};

/** ISO timestamp for a route, or undefined when history is unknown. */
export function lastmodFor(path: string): string | undefined {
  return ROUTE_LASTMOD[path];
}
`;

const previous = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (previous !== body) {
  writeFileSync(OUT, body);
  console.log(`[lastmod] wrote ${path.relative(root, OUT)}`);
} else {
  console.log("[lastmod] already up to date.");
}
