/* eslint-disable -- auto-generated by TanStack Router; do not edit by hand, all rules disabled intentionally */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitlistConfirmRouteImport } from './routes/waitlist/confirm'
import { Route as PrivacyVerifyRouteImport } from './routes/privacy/verify'
import { Route as PrivacyRequestRouteImport } from './routes/privacy/request'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/_staff'
import { Route as DotwellKnownSecurityDottxtRouteImport } from './routes/[.]well-known.security[.]txt'
import { Route as ApiPublicInsightsDigestRouteImport } from './routes/api/public/insights-digest'
import { Route as ApiPublicGuardMetricsRouteImport } from './routes/api/public/guard-metrics'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiPublicCspDashboardRouteImport } from './routes/api/public/csp-dashboard'
import { Route as ApiPublicCspAlertCheckRouteImport } from './routes/api/public/csp-alert-check'
import { Route as AuthenticatedStaffInsightsRouteImport } from './routes/_authenticated/_staff.insights'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistConfirmRoute = WaitlistConfirmRouteImport.update({
  id: '/waitlist/confirm',
  path: '/waitlist/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyVerifyRoute = PrivacyVerifyRouteImport.update({
  id: '/privacy/verify',
  path: '/privacy/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRequestRoute = PrivacyRequestRouteImport.update({
  id: '/privacy/request',
  path: '/privacy/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotwellKnownSecurityDottxtRoute =
  DotwellKnownSecurityDottxtRouteImport.update({
    id: '/.well-known/security.txt',
    path: '/.well-known/security.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInsightsDigestRoute = ApiPublicInsightsDigestRouteImport.update({
  id: '/api/public/insights-digest',
  path: '/api/public/insights-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGuardMetricsRoute = ApiPublicGuardMetricsRouteImport.update({
  id: '/api/public/guard-metrics',
  path: '/api/public/guard-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspDashboardRoute = ApiPublicCspDashboardRouteImport.update({
  id: '/api/public/csp-dashboard',
  path: '/api/public/csp-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspAlertCheckRoute = ApiPublicCspAlertCheckRouteImport.update({
  id: '/api/public/csp-alert-check',
  path: '/api/public/csp-alert-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffInsightsRoute =
  AuthenticatedStaffInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/account': typeof AuthenticatedAccountRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/privacy/verify': typeof PrivacyVerifyRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/insights': typeof AuthenticatedStaffInsightsRoute
  '/api/public/csp-alert-check': typeof ApiPublicCspAlertCheckRoute
  '/api/public/csp-dashboard': typeof ApiPublicCspDashboardRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/guard-metrics': typeof ApiPublicGuardMetricsRoute
  '/api/public/insights-digest': typeof ApiPublicInsightsDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/account': typeof AuthenticatedAccountRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/privacy/verify': typeof PrivacyVerifyRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/insights': typeof AuthenticatedStaffInsightsRoute
  '/api/public/csp-alert-check': typeof ApiPublicCspAlertCheckRoute
  '/api/public/csp-dashboard': typeof ApiPublicCspDashboardRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/guard-metrics': typeof ApiPublicGuardMetricsRoute
  '/api/public/insights-digest': typeof ApiPublicInsightsDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/communities': typeof CommunitiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/.well-known/security.txt': typeof DotwellKnownSecurityDottxtRoute
  '/_authenticated/_staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/privacy/request': typeof PrivacyRequestRoute
  '/privacy/verify': typeof PrivacyVerifyRoute
  '/waitlist/confirm': typeof WaitlistConfirmRoute
  '/_authenticated/_staff/insights': typeof AuthenticatedStaffInsightsRoute
  '/api/public/csp-alert-check': typeof ApiPublicCspAlertCheckRoute
  '/api/public/csp-dashboard': typeof ApiPublicCspDashboardRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/guard-metrics': typeof ApiPublicGuardMetricsRoute
  '/api/public/insights-digest': typeof ApiPublicInsightsDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/communities'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/trust'
    | '/.well-known/security.txt'
    | '/account'
    | '/privacy/request'
    | '/privacy/verify'
    | '/waitlist/confirm'
    | '/insights'
    | '/api/public/csp-alert-check'
    | '/api/public/csp-dashboard'
    | '/api/public/csp-report'
    | '/api/public/guard-metrics'
    | '/api/public/insights-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/communities'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/trust'
    | '/.well-known/security.txt'
    | '/account'
    | '/privacy/request'
    | '/privacy/verify'
    | '/waitlist/confirm'
    | '/insights'
    | '/api/public/csp-alert-check'
    | '/api/public/csp-dashboard'
    | '/api/public/csp-report'
    | '/api/public/guard-metrics'
    | '/api/public/insights-digest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/auth'
    | '/communities'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/robots.txt'
    | '/security'
    | '/sitemap.xml'
    | '/trust'
    | '/.well-known/security.txt'
    | '/_authenticated/_staff'
    | '/_authenticated/account'
    | '/privacy/request'
    | '/privacy/verify'
    | '/waitlist/confirm'
    | '/_authenticated/_staff/insights'
    | '/api/public/csp-alert-check'
    | '/api/public/csp-dashboard'
    | '/api/public/csp-report'
    | '/api/public/guard-metrics'
    | '/api/public/insights-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  CommunitiesRoute: typeof CommunitiesRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  DotwellKnownSecurityDottxtRoute: typeof DotwellKnownSecurityDottxtRoute
  PrivacyRequestRoute: typeof PrivacyRequestRoute
  PrivacyVerifyRoute: typeof PrivacyVerifyRoute
  WaitlistConfirmRoute: typeof WaitlistConfirmRoute
  ApiPublicCspAlertCheckRoute: typeof ApiPublicCspAlertCheckRoute
  ApiPublicCspDashboardRoute: typeof ApiPublicCspDashboardRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicGuardMetricsRoute: typeof ApiPublicGuardMetricsRoute
  ApiPublicInsightsDigestRoute: typeof ApiPublicInsightsDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/confirm': {
      id: '/waitlist/confirm'
      path: '/waitlist/confirm'
      fullPath: '/waitlist/confirm'
      preLoaderRoute: typeof WaitlistConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/verify': {
      id: '/privacy/verify'
      path: '/privacy/verify'
      fullPath: '/privacy/verify'
      preLoaderRoute: typeof PrivacyVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/request': {
      id: '/privacy/request'
      path: '/privacy/request'
      fullPath: '/privacy/request'
      preLoaderRoute: typeof PrivacyRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_staff': {
      id: '/_authenticated/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/security.txt': {
      id: '/.well-known/security.txt'
      path: '/.well-known/security.txt'
      fullPath: '/.well-known/security.txt'
      preLoaderRoute: typeof DotwellKnownSecurityDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/insights-digest': {
      id: '/api/public/insights-digest'
      path: '/api/public/insights-digest'
      fullPath: '/api/public/insights-digest'
      preLoaderRoute: typeof ApiPublicInsightsDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/guard-metrics': {
      id: '/api/public/guard-metrics'
      path: '/api/public/guard-metrics'
      fullPath: '/api/public/guard-metrics'
      preLoaderRoute: typeof ApiPublicGuardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-dashboard': {
      id: '/api/public/csp-dashboard'
      path: '/api/public/csp-dashboard'
      fullPath: '/api/public/csp-dashboard'
      preLoaderRoute: typeof ApiPublicCspDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-alert-check': {
      id: '/api/public/csp-alert-check'
      path: '/api/public/csp-alert-check'
      fullPath: '/api/public/csp-alert-check'
      preLoaderRoute: typeof ApiPublicCspAlertCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_staff/insights': {
      id: '/_authenticated/_staff/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedStaffInsightsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
  }
}

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffInsightsRoute: typeof AuthenticatedStaffInsightsRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffInsightsRoute: AuthenticatedStaffInsightsRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  CommunitiesRoute: CommunitiesRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  DotwellKnownSecurityDottxtRoute: DotwellKnownSecurityDottxtRoute,
  PrivacyRequestRoute: PrivacyRequestRoute,
  PrivacyVerifyRoute: PrivacyVerifyRoute,
  WaitlistConfirmRoute: WaitlistConfirmRoute,
  ApiPublicCspAlertCheckRoute: ApiPublicCspAlertCheckRoute,
  ApiPublicCspDashboardRoute: ApiPublicCspDashboardRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicGuardMetricsRoute: ApiPublicGuardMetricsRoute,
  ApiPublicInsightsDigestRoute: ApiPublicInsightsDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
